### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by JelleZijlstra** [aio-libs/aiozmq#131]
This project has been moved into an "abandoned" organization and doesn't seem to have any activity recently.

Is there still interest in getting it back to a working state? If I am interested in maintaining it going forward, could I continue to release it under the `aiozmq` name?

**Comment by asvetlov** [comment]
If you want to maintain it -- you are welcome.
I could transfer ownership to you or move the project back to aio-libs with granting you admin access rights.

**Comment by JelleZijlstra** [comment]
Sounds good, either way (aiolibs or placing it under my user) is fine with me.

I'll be able to do maintenance and review pull requests, but likely won't do much forward development. Hopefully that'll be enough to keep the project alive.

**Comment by asvetlov** [comment]
Moved back to `aio-libs`.
Perhaps we need to restore back Travis.
@webknjaz please help us to register/migrate the project on `travis-ci.com`.
@JelleZijlstra you are the project admin now.
Feel free to ask any help.

**Comment by JelleZijlstra** [comment]
Thanks! Looks like Travis is running fine but the code bitrotted; I'll fix that first.

I might need help getting a release out, but first I'll try to get the build passing.

**Comment by asvetlov** [comment]
Good

**Comment by webknjaz** [comment]
@JelleZijlstra you might need to regenerate secrets in Travis CI config, but it looks like @asvetlov has already done this.
CI config itself might use some refactoring though. Like separation of linters into a dedicated job.

**Comment by webknjaz** [comment]
Oh, it's still @ .org for some reason.
@asvetlov maybe you need to enable it @ https://github.com/organizations/aio-libs/settings/installations/149775 (I don't have access). Try it. If not, I'll email travis about it.

**Comment by asvetlov** [comment]
It is enabled for all repos.
I afraid email to travis support is needed (as you did for all other repos before)

**Comment by webknjaz** [comment]
Is this repo there on the list?

**Comment by webknjaz** [comment]
I've texted @travis-ci asking them to migrate the repo.

**Comment by JelleZijlstra** [comment]
Sorry, what exactly does Travis need to change? Travis already runs for this repo, though I noticed that I don't have admin access to cancel/re-run builds.

**Comment by webknjaz** [comment]
They need to migrate the repo to .com site.

**Comment by webknjaz** [comment]
Badge in README needs updating

**Comment by JelleZijlstra** [comment]
Will fix in #144.

**Comment by JelleZijlstra** [comment]
@asvetlov I'm (finally) getting ready to release a new version of aiozmq, but it turns out I don't have permissions on pypi. Could you add me to https://pypi.org/project/aiozmq/ ? Thanks!

**Comment by webknjaz** [comment]
@JelleZijlstra actually, it's a bot account that needs to be added: https://github.com/aio-libs/aiozmq/blob/9a81564
/.travis.yml#L52-L55. Manual uploads are not recommended.

**Comment by asvetlov** [comment]
That's true, in aio-libs we prefer CI uploaded release, the upload is triggered by pushing Git tag.
@JelleZijlstra is free to select another schema if he wants, he is the project maintainer.
Please tell me your login name on PyPI, I'll add you to the project.

**Comment by JelleZijlstra** [comment]
It's https://pypi.org/user/JelleZijlstra/, thanks!

@webknjaz is right though that it would be better for a bot to do the uploading. If you can give the bot upload permissions again, that would be even better.

**Comment by asvetlov** [comment]
@JelleZijlstra 
I've added you to the PyPI project as "Owner".
Also, I've updated `.travis.yml` to use a new PyPI upload token feature and released `aiozmq==0.9.0a0`.
If everything will go smoothly we'll see the autouploaded release on PyPI.

**Comment by asvetlov** [comment]
Yes, everything is fine: https://pypi.org/project/aiozmq/0.9.0a0/#files

Release process: 
1. Bump the version number in `__init__.py`.
2. Update `./CHANGES.txt`
3. Make git tag `git tag -a v0.9.0a0 -m "Release 0.9.0a0". Please note: the tag is prefixed with `v`, this is the usual rule for GitHub.
4. Push git tag on GitHub.
5. Wait for Travis CI finish for the pushed tag.
6. Enjoy
