### ISSUE TITLE
Drop python < 3.5.3 support

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiozmq#141]
I think it is time to drop 3.3/3.4 support this will also reduce CI time.

**Comment by JelleZijlstra** [comment]
I already dropped 3.3. Shouldn't we wait with 3.4 until it reaches EOL though?

**Comment by jettify** [comment]
Most of aio-libs projects dropped 3.3/3.4 support, this allows us to use new coroutines syntax.

**Comment by JelleZijlstra** [comment]
I see, in that case it makes sense to drop 3.4 too. What is the motivation for 3.5.3 specifically? The Python docs list a couple of things that were changed in 3.5.3 but nothing that sounds essential.

**Comment by asvetlov** [comment]
`asyncio.get_event_loop()` returns a running loop (not default or installed by `asyncio.set_event_loop()`) when called from a coroutine.
