### ISSUE TITLE
Process hangs with 100% CPU after several weeks uptime

### ISSUE THREAD

**Issue by diefans** [aio-libs/aiozmq#160]
I have a zmq worker hanging after several weeks running fine:
```
# strace -p 32709 -f 
strace: Process 32709 attached with 4 threads
strace: [ Process PID=32709 runs in x32 mode. ]
[pid 32712] epoll_pwait(15,  <unfinished ...>
[pid 32711] epoll_pwait(12,  <unfinished ...>
[pid 32710] futex(0x234d9e0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff
```
If anybody has a hint howto proceed, let me know....

**Comment by JelleZijlstra** [comment]
Seems like the fourth (main) thread is not doing any syscalls. You could try running `gdb -p 32709` and running `bt` to figure out what it's doing.

**Comment by diefans** [comment]
ok found the bug... sorry for the noise... nothing to see here ;)
