### ISSUE TITLE
Prepare 1.0 release

### ISSUE THREAD

**Issue by JelleZijlstra** [aio-libs/aiozmq#166]
I'm planning to cut a 1.0 release in the near-ish future that makes a few major changes:
- Drop support for Python 3.5
- Use modern asyncio APIs only: no `@coroutine`, no explicit `loop=` passing
- Drop support for using type annotations as conversion functions in RPC calls (since it conflicts with using them as actual type annotations)

If you're using this library and this will cause problems for you, please let me know. I'm serving as the maintainer for this library because I use it in one of my projects, but I don't have time to do much more than making sure it keeps working with new Python versions. The 1.0 tag will be just in order to justify a backwards compatibility break (for the type annotations), not to signal any new features.

**Comment by PengyiPan** [comment]
Do you have any estimation on the release date of 1.0 atm? thx

**Comment by JelleZijlstra** [comment]
Not really, I haven't prioritized working on this because the current state of aiozmq isn't really causing me problems. I'd welcome PRs implementing the changes I listed above.

**Comment by kPsarakis** [comment]
In Python 3.11, `@asyncio.coroutine` does not exist anymore, leading to `AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?` this makes this release necessary for Python 3.11 support. 

Thanks for all the work you have done with this package.

**Comment by JelleZijlstra** [comment]
The test suite now passes under 3.10 and 3.11. There are still some deprecations but I think fixing those can wait.

That leaves removing the parameter conversion stuff, for which I opened #182. After that lands I will cut a release.

**Comment by JelleZijlstra** [comment]
I released https://pypi.org/project/aiozmq/1.0.0/

**Comment by kPsarakis** [comment]
Thanks a lot! Much appreciated
