### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by musicinmybrain** [aio-libs/aiozmq#172]
Explicit loop parameters, [deprecated since Python 3.8](https://bugs.python.org/issue36373), will be removed throughout the public asyncio APIs in Python 3.10. See also [this overview on StackOverflow](https://stackoverflow.com/questions/60312374/what-are-all-these-deprecated-loop-parameters-in-asyncio). This causes widespread test failures in `aiozmq` with the available pre-release versions of Python 3.10.

I was considering taking over maintaining the `python-aiozmq` package in Fedora Linux, which was recently “orphaned,” but I can’t keep it in the distribution without a path forward for Python 3.10, and the needed changes seem not-quite-trivial (else I would just offer a quick PR).

Any thoughts? Thanks!

**Comment by musicinmybrain** [comment]
Now I see that you already mentioned dropping explicit loop parameters in https://github.com/aio-libs/aiozmq/issues/166. Please feel free to close this as a duplicate if you like.

**Comment by JelleZijlstra** [comment]
Yes, I need to get back to working on this, thanks for the reminder!

Any PRs implementing some of this would be appreciated.

**Comment by weaming** [comment]
works on branch master!

**Comment by JelleZijlstra** [comment]
Fixed in the latest release: https://pypi.org/project/aiozmq/1.0.0/
