### ISSUE TITLE
Interest in man pages?

### ISSUE THREAD

**Issue by musicinmybrain** [aio-libs/aiozmq#173]
I’ve written a set of basic man pages in `groff_man(7)` format for `aiozmq-proxy`, based on the `--help` output of `aiozmq-proxy` and its subcommands. You can take a look at them [here](https://src.fedoraproject.org/rpms/python-aiozmq/tree/d84ae60163cf34e74b1706d3e332c25636424883). Is there any interest in maintaining these upstream? If so, I’m happy to offer them in a PR.

If so, my default approach would be just to drop them in a `man/` directory and add them to `MANIFEST.in` so they are in the source archive, since installing man pages is not generally something Python packages can do reliably.

**Comment by JelleZijlstra** [comment]
Thanks for the offer! I'm already not finding much time for maintaining this project and I know nothing about man pages, so it's not a burden I'd like to add to the project.

**Comment by musicinmybrain** [comment]
That’s reasonable. Thanks!
