### ISSUE TITLE
Python 3.10: wait_for() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by nirvana-msu** [aio-libs/aiozmq#175]
Python 3.10 removed the loop parameter from a number of asyncio coroutines, including e.g. `wait_for`. Most have been deprecated since 3.8. `aiozmq` still explicitly passes `loop` in some cases, breaking the code in 3.10.

I can see you've removed some of them in https://github.com/aio-libs/aiozmq/commit/a9d70f1f45f3493450a4f9d6fff0507894037651, but not all.

E.g. my code is failing at:
https://github.com/aio-libs/aiozmq/blob/1cde8c6831d63e6a778390ce1ce422d6d27f2ab8/aiozmq/rpc/util.py#L25

**Comment by JelleZijlstra** [comment]
Fixed in the latest release, https://pypi.org/project/aiozmq/1.0.0/
