### ISSUE TITLE
New release for python 3.11

### ISSUE THREAD

**Issue by kPsarakis** [aio-libs/aiozmq#180]
Hi! 

Thanks a lot for all the work you did with this package. 

Is it possible to make a new release for `python 3.11`? 

The reason that installation fails for `3.11` is that `@asyncio.coroutine` does not exist anymore, leading to: 

`AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?`

I currently perform the installation with the latest commit hash, which works for python `3.11.0`.

Let me know if I can help in any way.

**Comment by JelleZijlstra** [comment]
I haven't been able to spend much time on this package but I hope to finish the plan from #166 and get a release out. I'll comment there with what remains to be done.

**Comment by JelleZijlstra** [comment]
Just released https://pypi.org/project/aiozmq/1.0.0/
