### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jdavid** [aio-libs/aiozmq#48]
Hello,

I hit the bug fixed in commit dcdf4c8bc46 while installing another software that makes use
of aiozmq. Steps to reproduce:

    $ virtualenv -p /usr/bin/python3.4 xbus
    $ ./xbus/bin/pip install xbus.broker
    $ ./xbus/bin/start_xbusbroker
    Traceback (most recent call last):
    [...]
    File "[...]/xbus/lib/python3.4/site-packages/aiozmq/core.py", line 211, in _BaseTransport
      zmq.STREAM: 'STREAM'}
    AttributeError: 'module' object has no attribute 'STREAM'

Any plans for a new release?

Thanks.

**Comment by asvetlov** [comment]
Released 0.6.1
