### ISSUE TITLE
transport.connect with a DNS name fails -- works with a pre-made zmq_sock

### ISSUE THREAD

**Issue by elonen** [aio-libs/aiozmq#56]
Connecting a (Dealer) socket with a DNS name raises `ValueError: 'example.com' does not appear to be an IPv4 or IPv6 address`:

    import zmq, aiozmq, asyncio
    def test():
      socket = yield from aiozmq.create_zmq_stream(zmq.DEALER)
      socket.transport.setsockopt(zmq.IDENTITY, b'myidentity')
      yield from socket.transport.connect('tcp://example.com:1234')
    asyncio.get_event_loop().run_until_complete(test())

The following works, however:

    context = zmq.Context()
    zmq_socket = context.socket(zmq.DEALER)
    zmq_socket.setsockopt(zmq.IDENTITY, b'myidentity')
    zmq_socket.connect('tcp://example.com:1234')
    socket = yield from aiozmq.create_zmq_stream(zmq.DEALER, zmq_sock=zmq_socket)

Versions:
aiozmq==0.6.1
pyzmq==14.7.0

**Comment by asvetlov** [comment]
Fixed. Try new 0.7 release
