### ISSUE TITLE
await branch like aiopg

### ISSUE THREAD

**Issue by MetaMemoryT** [aio-libs/aiozmq#59]
Could aiozmq have an await branch to demonstrate examples using the new syntax?

Using async def and await everywhere?

**Comment by asvetlov** [comment]
Just for examples?

**Comment by MetaMemoryT** [comment]
I was looking at aiopg branch: https://github.com/aio-libs/aiopg/compare/await

It looks like __aenter__ and __aexit__ have to be defined for all classes, also.

**Comment by asvetlov** [comment]
If somebody have concrete proposal -- please create a Pull Request
