### ISSUE TITLE
Appropriate msgpack-python not installed

### ISSUE THREAD

**Issue by ariddell** [aio-libs/aiozmq#60]
I just did a ``pip install aiozmq`` and the requirement ``msgpack-python>=0.4`` was not enforced:

```
pip install aiozmq

Collecting aiozmq
  Downloading aiozmq-0.7.1-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pyzmq>=13.1 in /usr/lib/python3/dist-packages (from aiozmq)
Installing collected packages: aiozmq
Successfully installed aiozmq-0.7.1

python test1.py

...

ImportError: cannot import name 'ExtType'
```

Yet I see the appropriate lines in ``setup.py``. I'm not sure what could have gone wrong.

**Comment by popravich** [comment]
`msgpack` is optional requirement which is needed for `aiozmq.rpc` package (which is optional as well).
Try re-installing `aiozmq` with explicit extra requirement:
```
pip install aiozmq[rpc]
```
See http://pip.readthedocs.org/en/stable/reference/pip_install/#examples point 6.

**Comment by ariddell** [comment]
My mistake! Thanks.

**Comment by popravich** [comment]
no problem)
